# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: "From raw data to kinetic parameters: an EnzymeML-based workflow for reproducible enzyme kinetics"
author: Max Häußler

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations

# Information about where the book exists on the web
repository:
  url: https://github.com/haeussma/masterthesis # Online location of your book
  path_to_book: book # Optional path to your book, relative to the repository root
  branch: master # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  #use_issues_button: true
  use_repository_button: true

sphinx:
  local_extensions:
    apastyle: _citations/
    bracket_citation_style: _citations/
  config:
    bibtex_default_style: myapastyle
    bibtex_reference_style: author_year_round
    html_show_copyright: false

bibtex_reference_style: author_year_round
bibtex_default_style: myapastyle
bibtex_bibfiles: references.bib

parse:
  myst_enable_extensions:
    # don't forget to list any other extensions you want enabled,
    # including those that are enabled by default!
    - amsmath
    - dollarmath
